name: 构建并发布Docker镜像

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Go环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: 安装UPX
      run: sudo apt-get update && sudo apt-get install -y upx

    - name: 构建Go程序
      run: go build -o aiload -ldflags -w main.go

    - name: 使用UPX压缩可执行文件
      run: upx -9 aiload

    - name: 登录到Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 构建并推送Docker镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/aiload:latest